export const EVENTS = {
  START_GAME: "react:start-game",
  RESUME_GAME: "react:resume-game",
  PAUSE_FOR_POWER_SHOP: "react:pause-for-power-shop",
  RESTART_GAME: "react:restart-game",
  CONTINUE_LEVEL: "react:continue-level",
  GO_TO_MENU: "react:go-to-menu",
  ACTIVE_LEVEL_CHANGED: "game:active-level-changed",
  SFX_REQUESTED: "game:sfx-requested",
  HAPTIC_REQUESTED: "game:haptic-requested",
  HUD_UPDATED: "game:hud-updated",
  HEALTH_PICKUP_COLLECTED: "game:health-pickup-collected",
  PLAYER_DAMAGED: "game:player-damaged",
  PLAYER_LEVELED_UP: "game:player-leveled-up",
  ACHIEVEMENT_UNLOCKED: "game:achievement-unlocked",
  SCREEN_CHANGED: "game:screen-changed",
  LEVEL_COMPLETED: "game:level-completed",
} as const;
